In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1, 2, 3, 4])
a
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])
a.dtype

Check numpy version

In [ ]:
print(np.__version__)

Changing element

In [ ]:
a[4] = 1000
a

Slicing

In [ ]:
d = a[1:4]
d

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0:9:3]) #[start:end:step]

Numpy Array Operations

In [ ]:

u = np.array([1, 0])
u
v = np.array([0, 1])
v
# Numpy Array Addition
z = np.add(u, v)
z
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr12 = np.add(arr1,arr2)
arr12

In [ ]:
# Plotting functions
import time 
import sys
import numpy as np 
import matplotlib.pyplot as plt

def Plotvec1(u, z, v):
    
    ax = plt.axes() # to generate the full window axes
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)# Add an arrow to the  U Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(u + 0.1), 'u')#Adds the text u to the Axes 
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)# Add an arrow to the  v Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(v + 0.1), 'v')#Adds the text v to the Axes 
    
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')#Adds the text z to the Axes 
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)

# Plot numpy arrays
Plotvec1(u, z, v)

In [ ]:
# array subtraction
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr1_minus2 = np.subtract(arr2,arr1)
arr1_minus2

In [ ]:
# Numpy Array Multiplication
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
multiply = np.multiply(arr1,arr2)
multiply

In [ ]:
# Numpy Array Division
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
division = np.divide(arr1,arr2)
division


In [ ]:
# Calculate the dot product
X = np.array([1, 2])
Y = np.array([3, 2])
np.dot(X, Y)




In [ ]:
# Create a constant to numpy array
u = np.array([1, 2, 3, -1]) 
u
u + 1


In [ ]:
# The value of pi
np.pi

In [ ]:
# Create the numpy array in radians
x = np.array([0, np.pi/2 , np.pi])


In [ ]:
# Calculate the sin of each elements

y = np.sin(x)
y

In [ ]:
# Linspace - returns evenly spaced numbers over a specified interval
# numpy.linspace(start, stop, num = int value)
#   start : start of interval range
#   stop : end of interval range
#   num : Number of samples to generate.

# Makeup a numpy array within [-2, 2] and 5 elements
np.linspace(-2, 2, num=5)

# Make a numpy array within [0, 2π] and 100 elements 
x = np.linspace(0, 2*np.pi, num=100)
x

# Calculate the sine of x list
y = np.sin(x)
plt.plot(x, y)



In [ ]:
# Iterating 1-D Arrays
arr1 = np.array([1, 2, 3])
print(arr1)

for x in arr1:
  print(x)

Matrix in numpy

In [50]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
#  Convert to a numpy array
npa = np.array(a)
npa



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
# Calculate the numpy array size
np.size(npa)

12

In [53]:
# Access the element on the first row and first and second columns
npa[0][0:2]


array([1, 2])

In [58]:
a

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [ ]:
# matrix multiplication with the numpy arrays

b = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
c = np.dot(a,b)
c

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

In [61]:
a=np.array([-1,1]) 
b=np.array([1,1]) 

c = np.dot(a,b) 


0


In [ ]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,1],[1,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 1],
       [1, 2]])

: 